### ISSUE TITLE
Display file contents

### ISSUE THREAD

**Issue by rowland007** [rowland007/Zoo-Infrastructure#6]
### Gives authenticated users access to the correct role file after successful authentication
* The system information stored in the role file should be displayed. For example, if a _zookeeper_’s credentials is successfully authenticated, then the contents from the `zookeeper file` will be displayed. If an _admin_’s credentials is successfully authenticated, then the contents from the `admin file` will be displayed.
- [x] Compares username to file name
- [x] scan file into memory
- [x] display file on monitor

**Comment by rowland007** [comment]
Error getting file
Exception in thread "main" java.lang.NullPointerException
	at com.randarlabs.common.TextReader.closeFile(TextReader.java:51)
	at edu.snhu.Main.showUserFile(Main.java:81)
	at edu.snhu.Main.logInScreen(Main.java:71)
	at edu.snhu.Main.main(Main.java:43)
null

Process finished with exit code 1

**Comment by rowland007** [comment]
Possible error could be trying to use the username and appending ```.txt``` to it.
Going to try and set a variable to hold each file and just call the variable that corresponds to the user's user group.

**Comment by rowland007** [comment]
The correct file is now located and displayed on the screen. However it will only display 1 line of text.  Creating new issue to cover it.
Issue #19
